.Phony: run
run:
	@echo "Running chat app"
	@cargo run

.Phony: build
build:
	@echo "Running chat app"
	@cargo build

.Phony: watch
watch:
	@echo "Running chat app"
	@npx nodemon --exec 'make run' --signal SIGTERM
